### ISSUE TITLE
Error on repo cloning 

### ISSUE THREAD

**Issue by kashishkhullar** [algorand/pyteal#497] opened 2022-08-09 01:24 UTC
### Subject of the issue

Getting the following error on cloning this repo on my local system

### Your environment

* Software version: `git --version` `2.35.1.windows.2`

### Steps to reproduce

1. Clone this repo

### Actual behaviour

Empty cloned folder with the following error on console.

```cmd
Resolving deltas: 100% (4290/4290), done.
error: invalid path 'tests/integration/teal/roundtrip/app_roundtrip_(bool,byte,address,string,(address,(uint32,string[],bool[2],(byte),uint8)[2],string,bool[]))[]_<2>.teal'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by tzaffi** [comment] 2022-08-10 13:05
Thanks @kashishkhullar for letting us know about this bug. 

This morning, I merged #499 which I believe has fixed the bug which you encountered. Please try again to clone the repo and let us know if the issue is indeed resolved.

**Closed** 2022-08-15 17:31 UTC
Labels: Team Scytale, new-bug
