### ISSUE TITLE
Support for ecdsa opcodes functionality

### ISSUE THREAD

**Issue by algoanne** [algorand/pyteal#160] opened 2022-01-14 20:07 UTC
**Context**
The TEAL `ecdsa_verify`, `ecdsa_pk_decompress` and `ecdsa_pk_recover` opcodes are available in TEAL but not yet PyTeal. 

**What are you looking for?**
All three opcodes' functionalities should be made available in PyTeal.

**(Optional) Design considerations**

**Comment by barnjamin** [comment] 2022-01-14 20:10
dupe of https://github.com/algorand/pyteal/issues/125

**Closed** 2022-01-14 20:59 UTC
Labels: Team Scytale
